version: "3"
   
services:

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    expose:
      - 5432 

  web:
    build: .
    env_file:
     - ./.env
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db