version: "3"
   
services:

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
        - pgdata:/var/lib/postgresql/data
    expose:
      - 5432 

  web:
    build: .
    restart: always
    container_name: djangoapp
    env_file:
     - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
        - ./:/var/vulkan


volumes:
    pgdata:
        driver: local