# Generated by Django 3.1 on 2020-10-12 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0004_sells'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=6)),
                ('shares', models.IntegerField()),
                ('share_price', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('unspecified', 'Unspecified'), ('buy', 'Buy'), ('sell', 'Sell')], default='unspecified', max_length=20, verbose_name='Transaction Type')),
                ('transaction_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
