# Generated by Django 3.1 on 2020-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sells',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
